### ISSUE TITLE
pair --init doesn't work

### ISSUE THREAD

**Issue by aaronjensen** [substantial/wemux-pair#4]
```
/Users/aaronjensen/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1573:in `stat': No such file or directory @ rb_file_s_stat - /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/lib/etc/sample_config.yml (Errno::ENOENT)
        from /Users/aaronjensen/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
        from /Users/aaronjensen/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1589:in `fu_each_src_dest0'
        from /Users/aaronjensen/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
        from /Users/aaronjensen/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/lib/wemux/pair/commands/create_sample_config.rb:18:in `copy_file'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/lib/wemux/pair/commands/create_sample_config.rb:11:in `execute'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/lib/wemux/pair/commands/command.rb:6:in `run'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/lib/wemux/pair/runner.rb:40:in `execute'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/lib/wemux/pair/runner.rb:17:in `run'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/gems/wemux-pair-0.0.2/bin/pair:5:in `<top (required)>'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/bin/pair:23:in `load'
        from /Users/aaronjensen/.rvm/gems/ruby-2.1.1@gemset/bin/pair:23:in `<main>'
```

**Comment by jshou** [comment]
I get this too.

**Comment by athal7** [comment]
same here
